### ISSUE TITLE
Getting an AttributeError due to package conflict

### ISSUE THREAD

**Issue by scrazzz** [oliver-ni/discord-ext-menus-views#2]
## Code
I'm using the code from the README and using it inside a cog.
```python
from discord.ext import commands

from discord.ext import menus
from discord.ext.menus.views import ViewMenuPages

class MySource(menus.ListPageSource):
    def __init__(self, data):
        super().__init__(data, per_page=4)

    async def format_page(self, menu, entries):
        offset = menu.current_page * self.per_page
        return '\n'.join(f'{i}. {v}' for i, v in enumerate(entries, start=offset))

class Testing(commands.Cog):
    def __init__(self, bot):
        self.bot

    @commands.command()
    async def view(self, ctx):
        pages = ViewMenuPages(source=MySource(range(1, 100)), clear_reactions_after=True)
        await pages.start(ctx)

def setup(bot):
    bot.add_cog(Testing(bot))
```

## Traceback
The error I get when trying to load the cog.
```py
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 627, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hana/cogs/testing.py", line 2, in <module>
    from discord.ext.menus.views import ViewMenuPages
  File "/usr/lib/python3.9/site-packages/discord/ext/menus/views/__init__.py", line 5, in <module>
    class ViewMenu(menus.Menu):
AttributeError: module 'discord.ext.menus' has no attribute 'Menu'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hana/cogs/admin.py", line 67, in _eval
    ret = await func()
  File "<string>", line 2, in func
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 699, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 630, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.testing' raised an error: AttributeError: module 'discord.ext.menus' has no attribute 'Menu' 
```
Any suggestions/workarounds for this?

**Comment by scrazzz** [comment]
Nvm fixed it by importing it properly.

```python
from discord.ext import commands, menus
from discord.ext.menus.views import ViewMenuPages
```
